### ISSUE TITLE
Correnct path to start the language server

### ISSUE THREAD

**Issue by katafrakt** [jjlee/rescript-mode#12]
I updated `rescript-vscode` recently after quite a while and it did not want to work. After some tinkering I fixed it by setting a path to `'("node" "/path/to/rescript-vscode/server/out/cli.js" "--stdio")` instead of `'("node" "/path/to/rescript-vscode/server/out/server.js" "--stdio")`.

I'd usually make a PR to fix the README instead of raising an issue, but in this case I'd prefer to have some confirmation from another user.

**Comment by glennsl** [comment]
The language server was released as a stand-alone npm package a few months ago, so the recommended approach now is to install `@rescript/language-server` globally and use that instead.

See https://github.com/rescript-lang/rescript-vscode/tree/master/server

I can update the readme to reflect that.
